version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
        - .:/var/www/html
    ports:
        - "9086:80"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3389:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PMA_PORT}:80"
    depends_on:
      - mysql
